version: '3'
services:
  from_task4:
    image: rekusha/devopspractice
    ports: 
      - 8050-8054:80
    restart: always
    links:
      - db
  java_task5:
    image: japp
    links:
      - from_task4
      - db
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes: 
      - ./pgdata:/var/lib/postgresql/data/pgdata
