---
- name: add key for repository
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: add to source list
  ansible.builtin.apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    state: present

- name: install
  apt:
    name:
      - postgresql-client-13
      - python3-psycopg2
    state: present
    update_cache: yes