apiVersion: v2
name: Project-task8-Deploy
description: Deploy with Kuber by two jets
type: application
version: 0.1.0
appVersion: "1.0"

keywords:
   - postgresql
   - wagtail

maintainers:
   - giturl: https://gitlab.com/rekusha/exadel_task8
   - container_registory: https://gitlab.com/rekusha/exadel_task8/container_registry
