---
apiVersion: v1
kind: Secret
metadata:
  name: task8-secret
type: Opaque
data:
  SQL_USER: {{ .Values.secrets.SQL_USER | b64enc }}
  SQL_PASSWORD: {{ .Values.secrets.SQL_PASSWORD | b64enc }}
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc }}
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | b64enc }}
