# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}
spec:
  selector:
    app: {{ .Values.db.name }}
  type: ClusterIP
  ports:
    - port: {{ .Values.db.service.port }}

--- 
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector:
    project: {{ .Values.app.name }}
  type: LoadBalancer
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
