- name: create postgres db container
  community.docker.docker_container:
    name: task6-postgres
    image: postgres:alpine
    container_default_behavior: no_defaults
    auto_remove: yes
    detach: yes
    ports:
      - "5432:5432"
    env:
      POSTGRES_PASSWORD: "{{ db_password }}"